import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "https://musicfun.it-incubator.app/api/1.0/",   headers:{
    'api-key':'cfb5bfa9-69d4-4439-9be6-0e61787bc84d'
  } });